=== Webpack 简易指南

简单来说，Webpack 是一个前端打包工具。随着众多 JavaScript 框架流行起来，Webpack 成为目前最受欢迎的模块化构建工具

运行以下命令安装 Webpack

```
npm install webpack webpack-cli --save-dev
```

创建入口文件 _entry.js_，运行 Webpack

```
./node_modules/.bin/webpack entry.js
```

Webpack 默认输出内容到 _dist/main.js_，如果想输出到 _assets/application.js_，可以运行

```
npx webpack entry.js -o assets/application.js
```

> `npx webpack` 可以理解为 `./node_modules/.bin/webpack` 的简化写法

创建 Webpack 配置文件 _webpackfile.js_

```javascript
const { join } = require('path')

module.exports = {
  entry: './entry.js',
  output: {
    filename: 'application.js',
    path: join(__dirname, 'assets')
  }
}
```

现在，运行 Webpack 的命令简化为

```
npx webpack --mode development
```

> Webpack 的 `mode` 选项有三个可选值：`development`、`production` 和 `none`，编译时，如果 `mode` 的值为 `production`，输出的内容会被简化（压缩）

Webpack 配置文件还支持以下写法

```javascript
const { join } = require('path')

module.exports = (environment => {
  return {
    entry: './entry.js',
    output: {
      filename: 'application.js',
      path: join(__dirname, 'assets')
    }
  }
})
```

代码中 `environment` 这个变量的值可以通过以下命令设置

```
npx webpack --mode development --env development
```

Webpack 允许开发者在配置文件中设置 `mode` 的值

```diff
 const { join } = require('path')

 module.exports = (environment => {
+  const mode = environment || 'development'
+
   return {
+    mode,
     entry: './entry.js',
     output: {
       filename: 'application.js',
```

代码中 `mode` 这个变量的默认值为 `development`

现在，运行 Webpack 的命令简化为

```
npx webpack
```

发布生产环境版本时，可以运行

```
npx webpack --env production
```

接下来，可以定制 _package.json_ 的 `scripts` 字段

```diff
   "scripts": {
+    "watch": "webpack --watch",
+    "build": "webpack --env production"
   },
```

> Webpack 的 `--watch` 选项表示启动监听模式

现在，运行 Webpack 的命令简化为

```
npm run watch
```

发布生产环境版本时，可以运行

```
npm run build
```

Webpack 自定义输出还支持以下写法

```diff
 module.exports = (environment => {
   const mode = environment || 'development'
+  const devMode = mode === 'development'

   return {
     mode,
     entry: './entry.js',
     output: {
-      filename: 'application.js',
-      path: join(__dirname, 'assets')
+      path: join(__dirname, 'assets'),
+      filename: devMode ? 'application.js' : 'application-[hash:12].js'
     }
   }
 })
```

这样一来，发布生产环境版本时，Webpack 输出文件的名称会加上长度为 12 的特征值（字符串）

在 Webpack 中，资源即模块，它们可以像 JavaScript 一样被引用

|===
| 资源位置 | 引用语法

| styles/index.js                   | require('babel-loader!./styles')
| node_modules/bulma/css/bulma.css  | require('css-loader!bulma/css/bulma.css')
| node_modules/lodash/capitalize.js | const capitalize = require('lodash/capitalize')
|===

不难看出，Webpack 对资源的处理依赖于各式各样的加载器

运行以下命令来安装 `babel-loader` 和 `css-loader`

```
npm install babel-loader @babel/core @babel/preset-env --save-dev
```

```
npm install css-loader mini-css-extract-plugin --save-dev
```

在 Webpack 配置文件中创建资源（模块）匹配规则

```diff
 const { join } = require('path')
+const MiniCssExtractPlugin = require('mini-css-extract-plugin')
```

```diff
     output: {
       path: join(__dirname, 'assets'),
       filename: devMode ? 'application.js' : 'application-[hash:12].js'
-    }
+    },
+    module: {
+      rules: [
+        {
+          test: /\.css$/,
+          use: [
+            {
+              loader: MiniCssExtractPlugin.loader
+            },
+            'css-loader'
+          ]
+        },
+        {
+          test: /\.js$/,
+          loader: 'babel-loader',
+          exclude: /node_modules/
+        }
+      ]
+    },
+    plugins: [
+      new MiniCssExtractPlugin({
+        filename: devMode ? 'application.css' : 'application-[hash:12].css'
+      })
+    ]
   }
 })
```

其中，`MiniCssExtractPlugin` 告诉 Webpack 样式内容要独立出来

由于 Webpack 会根据定义的规则自动选择加载器，为了避免歧义，以上语法简化为

|===
| 资源位置 | 引用语法

| styles/index.js                   | require('./styles')
| node_modules/bulma/css/bulma.css  | require('bulma/css/bulma.css')
| node_modules/lodash/capitalize.js | const capitalize = require('lodash/capitalize')
|===

使用 `html-webpack-plugin` 生成 _index.html_

```
npm install html-webpack-plugin --save-dev
```

在 Webpack 配置文件中加入这个插件

```diff
 const { join } = require('path')
+const HtmlWebpackPlugin = require('html-webpack-plugin')
```

```diff
     plugins: [
+      new HtmlWebpackPlugin({
+        filename: '../index.html'
+      }),
       new MiniCssExtractPlugin({
         filename: devMode ? 'application.css' : 'application-[hash:12].css'
       })
     ]
```

为了在浏览器访问 Webpack 生成的静态资源，安装以下工具

```
npm install serve --save-dev
```

> serve 提供一个简单的静态资源服务

启动服务器

```
serve -l 4300
```

现在，访问 http://localhost:4300 可以看到我们预想的效果
