=== Webpack 简易指南

简单来说，Webpack 是一个前端打包工具。随着众多 JavaScript 框架流行起来，Webpack 成为目前最受欢迎的模块化构建工具

你可以运行以下命令安装 Webpack

```
npm install webpack webpack-cli --save-dev
```

创建入口文件 _entry.js_，运行 Webpack

```
./node_modules/.bin/webpack entry.js
```

Webpack 默认会输出内容到 _dist/main.js_，如果想输出到 _assets/application.js_，可以运行

```
npx webpack entry.js -o assets/application.js
```

> `npx webpack` 可以理解为 `./node_modules/.bin/webpack` 的简化写法

为 Webpack 创建配置文件 _webpackfile.js_

```javascript
const { join } = require('path')

module.exports = {
  entry: './entry.js',
  output: {
    filename: 'application.js',
    path: join(__dirname, 'assets')
  }
}
```

有了以上的配置信息，运行 Webpack 的命令可以简化为

```
npx webpack --mode development
```

Webpack 的 `mode` 选项有三个可选值：`development`、`production` 和 `none`，当 `mode` 的值为 `production` 时，输出的内容会被简化（压缩）

Webpack 的配置文件还支持以下写法

```javascript
const { join } = require('path')

module.exports = (environment => {
  return {
    entry: './entry.js',
    output: {
      filename: 'application.js',
      path: join(__dirname, 'assets')
    }
  }
})
```

其中，`environment` 这个值可以通过以下命令设置

```
npx webpack --mode development --env development
```

不难看出，`mode` 和 `env` 参数几乎可以保持一致，因此可以去掉 `mode` 参数，并在配置文件中设置 `mode` 的值

```javascript
const { join } = require('path')

module.exports = (environment => {
  const mode = environment || 'development'
  const devMode = mode === 'development'

  return {
    mode,
    entry: './entry.js',
    output: {
      filename: 'application.js',
      path: join(__dirname, 'assets')
    }
  }
})
```

> 其中，`mode` 会有默认值 `development`，`devMode` 的值在接下来的配置需要用到

因此，在本地开发环境，仅需运行

```
npx webpack
```

在发布生产环境版本的时候，运行

```
npx webpack --env production
```

接下来，可以定制 _package.json_ 的 `scripts` 字段

```diff
"scripts": {
+  "watch": "webpack --watch",
+  "build": "webpack --env production"
},
```

> 这里的 `--watch` 会让 Webpack 启动监听模式

这样的话，有以下简化版本

在本地开发环境，仅需运行

```
npm run watch
```

在发布生产环境版本的时候，运行

```
npm run build
```

到目前为止，开发环境和生产环境输出的文件名都是 `application.js`，为了在生产环境中避免缓存问题，需要让每个版本的链接都不一样，也就是让生产环境输出的文件名都不一样

Webpack 每次编译时都会生成一个哈希值，输出内容有变化，这个哈希值就会不一样。因此，在配置文件中可以这样设置

```diff
output: {
-  filename: 'application.js',
-  path: join(__dirname, 'assets')
+  path: join(__dirname, 'assets'),
+  filename: devMode ? 'application.js' : 'application-[hash:12].js'
}
```

> 这样的 `[hash:12]` 表示哈希值（字符串）的长度为 12

前端开发离不开样式，接下来需要让 Webpack 支持加载 CSS 文件

```
npm install --save-dev css-loader
npm install --save-dev mini-css-extract-plugin
```

在配置文件中加入以下内容

```diff
+ const MiniCssExtractPlugin = require('mini-css-extract-plugin')
```

```javascript
output: {
  path: join(__dirname, 'assets'),
  filename: devMode ? 'application.js' : 'application-[hash:12].js'
- }
+ },
+ module: {
+   rules: [
+     {
+       test: /\.css$/,
+       use: [
+         {
+           loader: MiniCssExtractPlugin.loader
+         },
+         'css-loader'
+       ]
+     }
+   ]
+ },
+ plugins: [
+   new MiniCssExtractPlugin({
+     filename: devMode ? 'application.css' : 'application-[hash:12].css'
+   })
+ ]
```
