on:
  schedule:
    - cron: '5,15,25 7 * * *'
  workflow_dispatch:
jobs:
  daily:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: npm install
      - run: node melon-chart.js
        env:
          ID_2016: '<<ID_it_works>>'
