name: ig_go
on:
  workflow_dispatch:
jobs:
  curl:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: apt update
      - run: apt install curl
