name: Node.js CI
on:
  push:
  schedule:
    - cron: "*/2 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: node .github/actions/script_1.js
