name: Rake

on:
  schedule:
    - cron: '0 1-3 * * *'
  workflow_dispatch:

jobs:
  rake:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rake renew
