name: My Node Action
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  my-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          version: 15
      - run: node .github/actions/script_1.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
