name: 周刊
on:
  push:

jobs:
  weekly:
    name: weekly
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: node .github/actions/script_1.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
