name: YouTube WJSN

on:
  schedule:
    - cron: '5/20 * * * *'
  workflow_dispatch:

jobs:
  rake:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: gem install bundler
      - run: bundle install
      - run: ruby main.rb
        env:
          GITEE_TOKEN: ${{ secrets.GITEE_TOKEN }}
          JSONBIN_TOKEN: ${{ secrets.JSONBIN_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
